# docker requires super-user permissions
sudo: required
services:
  # make sure travis understands we need docker-cli pre-installed
  # travis will auto-install a copy of docker
  - docker
# series of commands executed before we start to either run tests or deploy project
before_install:
  # command to build our docker image
  - docker build -t nb1987/docker-react -f ./frontend/Dockerfile.dev ./frontend
# script section contains all the commands necessary to execute our test suite
# travis-ci will watch the output of each of these commands; if any one has a 
# return status code of something other than 0, travis will assume our test-suite
# failed to run properly
script:
  - docker run nb1987/docker-react npm run test