# docker requires super-user permissions
sudo: required
services:
  # make sure travis understands we need docker-cli pre-installed
  # travis will auto-install a copy of docker
  - docker
# series of commands executed before we start to either run tests or deploy project
before_install:
  # command to build our docker image
  - docker build -t nb1987/docker-react -f ./frontend/Dockerfile.dev ./frontend
# script section contains all the commands necessary to execute our test suite
# travis-ci will watch the output of each of these commands; if any one has a 
# return status code of something other than 0, travis will assume our test-suite
# failed to run properly
script:
  - docker run nb1987/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-755106058900"
  bucket_path: "docker-react"
  # any time we push code to branch master, deploy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_KEY_SECRET"